services:
  api:
    build: .
    container_name: pm_sync_controller_prod
    env_file:
      - .env.prod
    network_mode: "host"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /home/${HOST_USER}/${HOST_WORKSPACE}/:/home/${HOST_USER}/${HOST_WORKSPACE}/
    command:
      - sh
      - -c
      - |
        poetry run alembic upgrade head \
        && poetry run uvicorn app:app \
          --host 0.0.0.0 \
          --port $${PORT} \
          --reload
    restart: unless-stopped
